version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: wallet-analysis-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    networks:
      - wallet-analysis-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wallet-analysis-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - wallet-analysis-network
    restart: unless-stopped

networks:
  wallet-analysis-network:
    driver: bridge